### ISSUE TITLE
EADDRINUSE on compile

### ISSUE THREAD

**Issue by barbier** [webpackmonitor/webpackmonitor#48]
Hi!
I'm having an issue using webpack 3.x, everytime my project recompile, I have this error, looks like webpack try to open a new instance of Monitor on the same port. Any idea? I'm using as told on instructions.

**Comment by roachjc** [comment]
Hey @barbier! Make sure that the port that's being passed to webpack monitor is not being used by anything else (if you're not specifying, default is 8081). Otherwise maybe it opened once and is still running? Typically you'd insert webpack monitor as a plugin on your production config and only periodically launch the dashboard. Hope that helps 😀

**Comment by barbier** [comment]
I'm pretty sure the port is used only by Monitor. It opens with my project, the error happens when I change something on my application, using React, and Webpack recompiles it.
Is there anything I can provide to describe better what's going on?

Thanks for the reply! :)

**Comment by roachjc** [comment]
Ah OK I think I get it. Sounds like wpm is open and trying to open again on same port which causes the error. Try setting `launch: false` (or just leave out - false is default) and only setting to true specifically when you want to open the front end. Also the intention was really only to capture your production builds if you have two configs in your webpack config - the idea being that we are not so concerned about the state of the non-optimized dev builds. Hope that helps ... let me know if I can clarify further

**Comment by vedovelli** [comment]
Hello @roachjc ! How are you doing?! I hope fine!

Given your statement:

```the idea being that we are not so concerned about the state of the non-optimized dev builds. Hope that helps```

I assume Webpack Monitor is supposed to be used with production builds only, right? Thanks!

**Comment by roachjc** [comment]
Hey @vedovelli, doing good. Your assumption is correct! Thanks for checking us out! Jon
