### ISSUE TITLE
[ QUESTION ] Why default browser will open in a blank page?

### ISSUE THREAD

**Issue by ibbatta** [webpackmonitor/webpackmonitor#58]
If launch is set to true, the browser should launch with a selected url + port, not in blank.
Is there a way to collect data without launch browser? (ie. `{launch: false, collect:true}`)

**Comment by roachjc** [comment]
Hi @ibbatta. Yes, that should work. Or you can omit `launch` and `collect` from options as they are set `launch: false, collect:true` as default.

**Comment by ibbatta** [comment]
Yeah it "should" works, but actually opens a blank page from my default browser.
If I set "launch" false then it collects nothing
