### ISSUE TITLE
Support for hot reloading

### ISSUE THREAD

**Issue by jadennnn** [webpackmonitor/webpackmonitor#69]
I know this probably isn't the recommended/expected usecase, but I wanted to try this tool so I threw it in the dev webpack build. Unfortunately it breaks whenever webpack tries to hot-reload the project:
```
Webpack-Monitor is running on port 8082!                                                                                                                                                       
Press ctrl C to exit                                                                                                                                                                           
webpack: Compiling...                                                                                                                                                                          
Writing new build                                                                     
Hash: 9f0cec5a7ea780fc5f36                                                                                                        
Version: webpack 3.8.1                                                                                                                                                                      
Time: 2038ms
                               Asset       Size  Chunks                    Chunk Names
4cd6e0031a7e8177e6f7.hot-update.json   44 bytes          [emitted]
                             main.js     523 kB       1  [emitted]  [big]  main
                         manifest.js    31.1 kB       2  [emitted]         manifest
1.3d2ba17ba7be3958d65b.hot-update.js    4.54 kB       1  [emitted]         main
3d2ba17ba7be3958d65b.hot-update.json   43 bytes          [emitted]
                          index.html  313 bytes          [emitted]
 + 1 hidden asset
[./node_modules/webpack/hot ^\.\/log$] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
    + 397 hidden modules
Child html-webpack-plugin for "index.html":
                                   Asset      Size  Chunks             Chunk Names
    4cd6e0031a7e8177e6f7.hot-update.json  44 bytes          [emitted]
     + 1 hidden asset
       4 modules
webpack: Compiled successfully.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8082
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1344:14)
    at listenInCluster (net.js:1385:12)
    at Server.listen (net.js:1469:7)
    at Function.listen (/home/jae/code/editor.beat-react/node_modules/express/lib/application.js:618:24)
    at module.exports (/home/jae/code/editor.beat-react/node_modules/webpack-monitor/utils/server.js:24:7)
    at fs.writeFile (/home/jae/code/editor.beat-react/node_modules/webpack-monitor/monitor.js:124:34)
    at /home/jae/code/editor.beat-react/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:136:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
I use webpack-monitor as the following as my last plugin:
```js
                new WebpackMonitorPlugin({
                        capture: true, // -> default 'true'
                        //target: './monitor/stats.json', // default -> '../monitor/stats.json'
                        launch: true, // -> default 'false'
                        port: 8082, // default -> 8081
                })
```

I'm guessing it has something to do with webpack trying to launch another instance of the webpack-monitor server each time it hot-reloads, because setting `launch` to `false` works fine.

Thanks alot for such a great tool! I'll probably use this for test/prod builds regardless :).

**Comment by jeffkamo** [comment]
I'm having the same issue. Is there a work around?

**Comment by roachjc** [comment]
Hey @jaepd and @jaepd. Thank you for getting in touch! 

Yeah it won't work on hot reloading I'm afraid, and nor should it want to. But would be good to handle this a bit better than erroring ... so sorry for that!

As for a workaround, don't include it in the webpack config that runs hot reload. The idea is that wpm is really only worth using for production builds where your optimization will take effect and builds will only take place periodically. It's just to keep a record of your proper builds and a mechanism to refer to that record, rather than something you're going to be looking at as you write your project and while you're using hot reload.

Hope that is of some help! 

Thank you for your feedback! Defo will look at handling this more 'gracefully' 😬

**Comment by jeffkamo** [comment]
That makes a lot of sense! Moving the plugin to our production webpack config did the trick.

Thanks for clarifying!

**Comment by jadennnn** [comment]
Hey thanks for confirming & yes it would be nice to see a little message :)

**Comment by DanielRuf** [comment]
> production webpack config

This makes not much sense in production mode.

**Comment by DanielRuf** [comment]
Watch mode should be supported. Running this in production on a server is not a good idea.

**Comment by DanielRuf** [comment]
At least it seems the data is not reloaded. I started two webpack instances. One launches wpm and the other doesn't but writes / should write to the file.

But the client does not reload the new data. Even if I manually edit the json file and reload in the browser it does not work. And I guess this is the root problem.

See how the developers of jarvis do it
https://github.com/zouhir/jarvis/search?utf8=%E2%9C%93&q=hot&type=
