### ISSUE TITLE
WebpackMonitor seems dead 

### ISSUE THREAD

**Issue by wanbinkimoon** [webpackmonitor/webpackmonitor#71]
I use [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) for  most of my projects I tried to integrate this wonderful plugin in it but is seems not working; nothing is happening and on the port I chose there is no sign of life. 

This is the config I use:
```
    new WebpackMonitor({
      capture: true,
      target: '../monitor/stats.json',
      launch: true, 
      port: 3001, 
    }),
```

**Comment by mbehzad** [comment]
Hi @wanbinkimoon , this worked for me: 
i cloned the react-boilerplate 
\+ `npm run setup`
\+ `npm install --save-dev webpack-monitor`
in `...\react-boilerplate\internals\webpack\webpack.prod.babel.js` added
`const WebpackMonitor = require('webpack-monitor');` at the beginning and 
`new WebpackMonitor({
      capture: true,
      target: '../monitor/stats.json',
      launch: true, 
      port: 3001, 
    }),` at the end of plugins array right after `new OfflinePlugin ...`

then executed `npm run build` wich calls webpack with the prod setup / config file. and the webpack-monitor local server started on port 3001 after the bundling. Charts/Information for the first build were present.

**Comment by wanbinkimoon** [comment]
Yup I had already bone that but I didn't choose the right build mode to launch it, works perfectly now
