### ISSUE TITLE
Add option to ignore source maps

### ISSUE THREAD

**Issue by dhedgecock** [webpackmonitor/webpackmonitor#88]
Hello, love the plugin.

Currently my build data includes the emitted source map assets, it would be nice to have an option to ignore these.

I tried setting this in my webpack config to exclude the source maps:

```javascript
stats = {
    excludeAssets: assetName => assetName.includes('.map')
  }
```

The source maps are excluded from the console log info from the build, but are still in the webpack monitor data.

What are your thoughts on using the configured stats when creating the webpack monitor stats data? If there's interest I'd love to contribute a PR adding the feature.

**Comment by roachjc** [comment]
Hi @DHedgecock 😀. Thank you! This is a great idea and something that I had on my to-do list!

My feeling is there should be an option in the plugin `excludeSourceMaps` and it should default to `true`.

I have not looked into how one would go about excluding sourcemaps within the plugin but should be possible. For me, this is preferable than requiring the user to amend the webpack config file.

Would love to hear your thoughts. If you think this is a good idea and would like to do a PR just let me know. Would love your help!

**Comment by dhedgecock** [comment]
Sounds good. It looks like the emitted assets are checked against the parsed assets in the final step before output is written. My thought is to pass the plugin options to the `parseStats` call and if `excludeSourceMaps` is true, filter out any asset whose name has `.map`.

I'll submit a PR as soon as I can test. Would love to contribute 👍

**Comment by roachjc** [comment]
Sounds good to me!
